"""Delivery Note / Albarán template."""

from core.models import DeliveryNoteData

LABELS = {
    "en": {"title": "DELIVERY NOTE", "from": "From", "to": "Delivered To", "num": "Delivery #", "date": "Date", "ref": "Invoice Ref.", "item": "Item", "qty": "Quantity", "unit": "Unit", "notes": "Notes", "signature": "Received By (Signature)"},
    "es": {"title": "ALBARÁN DE ENTREGA", "from": "De", "to": "Entregado A", "num": "Albarán Nº", "date": "Fecha", "ref": "Ref. Factura", "item": "Concepto", "qty": "Cantidad", "unit": "Unidad", "notes": "Notas", "signature": "Recibido Por (Firma)"},
}

def render_delivery_note(data: DeliveryNoteData) -> str:
    L = LABELS.get(data.language, LABELS["en"])
    co = data.company
    cl = data.client
    rows = ""
    for item in data.items:
        rows += f'<tr><td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;">{item.description}</td><td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{item.quantity:g}</td><td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{item.unit}</td></tr>'
    ref_html = f'<tr><td style="padding:4px 0;color:#6b7280;font-size:13px;">{L["ref"]}</td><td style="padding:4px 0 4px 16px;font-size:13px;">{data.invoice_reference}</td></tr>' if data.invoice_reference else ""
    notes_html = f'<div style="margin-top:24px;"><div style="font-weight:600;color:#374151;margin-bottom:4px;">{L["notes"]}</div><div style="color:#6b7280;font-size:13px;white-space:pre-line;">{data.notes}</div></div>' if data.notes else ""
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"/></head>
<body style="margin:0;padding:0;font-family:system-ui,-apple-system,sans-serif;color:#1f2937;font-size:14px;line-height:1.5;">
<div style="max-width:210mm;margin:0 auto;padding:40px 48px;">
<div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:40px;">
<div>{f'<img src="{co.logo_url}" style="max-height:60px;max-width:180px;margin-bottom:8px;" /><br/>' if co.logo_url else ''}<strong>{co.name}</strong>{f'<br/><span style="color:#6b7280;font-size:13px;">{co.address}</span>' if co.address else ''}{f'<br/><span style="color:#6b7280;font-size:13px;">{co.email}</span>' if co.email else ''}</div>
<div style="text-align:right;"><div style="font-size:28px;font-weight:700;color:#2563eb;letter-spacing:1px;margin-bottom:12px;">{L["title"]}</div>
<table style="margin-left:auto;border-collapse:collapse;"><tr><td style="padding:4px 0;color:#6b7280;font-size:13px;">{L["num"]}</td><td style="padding:4px 0 4px 16px;font-size:13px;font-weight:600;">{data.delivery_number}</td></tr><tr><td style="padding:4px 0;color:#6b7280;font-size:13px;">{L["date"]}</td><td style="padding:4px 0 4px 16px;font-size:13px;">{data.delivery_date}</td></tr>{ref_html}</table></div></div>
<div style="background:#f9fafb;border-radius:8px;padding:16px 20px;margin-bottom:32px;"><div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#9ca3af;margin-bottom:6px;">{L["to"]}</div><strong>{cl.name}</strong>{f'<br/><span style="color:#6b7280;font-size:13px;">{cl.address}</span>' if cl.address else ''}{f'<br/><span style="color:#6b7280;font-size:13px;">{cl.email}</span>' if cl.email else ''}</div>
<table style="width:100%;border-collapse:collapse;margin-bottom:24px;"><thead><tr style="background:#2563eb;color:white;"><th style="padding:10px 12px;text-align:left;font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:0.5px;border-radius:6px 0 0 0;">{L["item"]}</th><th style="padding:10px 12px;text-align:center;font-weight:600;font-size:12px;text-transform:uppercase;">{L["qty"]}</th><th style="padding:10px 12px;text-align:center;font-weight:600;font-size:12px;text-transform:uppercase;border-radius:0 6px 0 0;">{L["unit"]}</th></tr></thead><tbody>{rows}</tbody></table>
{notes_html}
<div style="margin-top:60px;display:flex;justify-content:flex-end;"><div style="width:280px;"><div style="font-weight:600;color:#374151;margin-bottom:40px;">{L["signature"]}</div><div style="border-top:1px solid #9ca3af;padding-top:8px;color:#6b7280;font-size:12px;">Name / Date</div></div></div>
<div style="margin-top:48px;text-align:center;color:#d1d5db;font-size:11px;">Generated by DocForge</div>
</div></body></html>"""
