"""Proposal template — document-style with sections, not a table."""

from core.models import ProposalData

LABELS = {
    "en": {"title": "PROJECT PROPOSAL", "prepared_for": "Prepared For", "prepared_by": "Prepared By", "date": "Date", "summary": "Executive Summary", "scope": "Scope of Work", "timeline": "Timeline", "investment": "Investment", "conditions": "Terms & Conditions"},
    "es": {"title": "PROPUESTA DE PROYECTO", "prepared_for": "Preparado Para", "prepared_by": "Preparado Por", "date": "Fecha", "summary": "Resumen Ejecutivo", "scope": "Alcance del Trabajo", "timeline": "Cronograma", "investment": "Inversión", "conditions": "Condiciones"},
}

def render_proposal(data: ProposalData) -> str:
    L = LABELS.get(data.language, LABELS["en"])
    co = data.company
    cl = data.client
    conditions_html = f'<div style="margin-top:28px;"><h3 style="color:#2563eb;font-size:16px;margin-bottom:8px;border-bottom:2px solid #e5e7eb;padding-bottom:6px;">{L["conditions"]}</h3><div style="color:#4b5563;font-size:13px;white-space:pre-line;">{data.conditions}</div></div>' if data.conditions else ""
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"/></head>
<body style="margin:0;padding:0;font-family:system-ui,-apple-system,sans-serif;color:#1f2937;font-size:14px;line-height:1.6;">
<div style="max-width:210mm;margin:0 auto;padding:40px 48px;">
<div style="text-align:center;margin-bottom:40px;padding-bottom:24px;border-bottom:3px solid #2563eb;">
<div style="font-size:32px;font-weight:700;color:#2563eb;letter-spacing:1px;margin-bottom:8px;">{L["title"]}</div>
<div style="font-size:20px;font-weight:600;color:#374151;">{data.project_title}</div>
<div style="margin-top:8px;color:#6b7280;font-size:13px;">{L["date"]}: {data.proposal_date}</div>
</div>
<div style="display:flex;gap:32px;margin-bottom:36px;">
<div style="flex:1;background:#f9fafb;border-radius:8px;padding:16px 20px;">
<div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#9ca3af;margin-bottom:6px;">{L["prepared_by"]}</div>
{f'<img src="{co.logo_url}" style="max-height:60px;max-width:180px;margin-bottom:8px;" /><br/>' if co.logo_url else ''}<strong>{co.name}</strong>{f'<br/><span style="color:#6b7280;font-size:13px;">{co.address}</span>' if co.address else ''}{f'<br/><span style="color:#6b7280;font-size:13px;">{co.email}</span>' if co.email else ''}
</div>
<div style="flex:1;background:#f9fafb;border-radius:8px;padding:16px 20px;">
<div style="font-size:11px;text-transform:uppercase;letter-spacing:1px;color:#9ca3af;margin-bottom:6px;">{L["prepared_for"]}</div>
<strong>{cl.name}</strong>{f'<br/><span style="color:#6b7280;font-size:13px;">{cl.address}</span>' if cl.address else ''}{f'<br/><span style="color:#6b7280;font-size:13px;">{cl.email}</span>' if cl.email else ''}
</div></div>
<div style="margin-top:28px;"><h3 style="color:#2563eb;font-size:16px;margin-bottom:8px;border-bottom:2px solid #e5e7eb;padding-bottom:6px;">{L["summary"]}</h3><div style="color:#4b5563;white-space:pre-line;">{data.summary}</div></div>
<div style="margin-top:28px;"><h3 style="color:#2563eb;font-size:16px;margin-bottom:8px;border-bottom:2px solid #e5e7eb;padding-bottom:6px;">{L["scope"]}</h3><div style="color:#4b5563;white-space:pre-line;">{data.scope}</div></div>
<div style="margin-top:28px;"><h3 style="color:#2563eb;font-size:16px;margin-bottom:8px;border-bottom:2px solid #e5e7eb;padding-bottom:6px;">{L["timeline"]}</h3><div style="color:#4b5563;white-space:pre-line;">{data.timeline}</div></div>
<div style="margin-top:28px;"><h3 style="color:#2563eb;font-size:16px;margin-bottom:8px;border-bottom:2px solid #e5e7eb;padding-bottom:6px;">{L["investment"]}</h3><div style="color:#4b5563;font-size:16px;font-weight:600;white-space:pre-line;">{data.investment}</div></div>
{conditions_html}
<div style="margin-top:48px;text-align:center;color:#d1d5db;font-size:11px;">Generated by DocForge</div>
</div></body></html>"""
